version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=onlineassessmentdb;User=root;Password=admin123;
      - Redis__Host=redis
      - Redis__Port=6379
      - Kafka__BootstrapServers=kafka:9092
      - JWT__Secret=THIS_IS_A_LONG_AND_SECURE_SECRET_KEY_32_CHARS
      - JWT__Issuer=yourdomain.com
      - JWT__Audience=yourdomain.com
    networks:
      - assessment-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=onlineassessmentdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - assessment-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - assessment-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - assessment-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - assessment-network

networks:
  assessment-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 