version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=onlineassessmentdb;User=root;Password=admin123;
      - JWT__Secret=THIS_IS_A_LONG_AND_SECURE_SECRET_KEY_32_CHARS
      - JWT__Issuer=yourdomain.com
      - JWT__Audience=yourdomain.com
    networks:
      - assessment-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=onlineassessmentdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - assessment-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  assessment-network:
    driver: bridge

volumes:
  mysql-data: 